import streamlit as st
import requests
import json
import os
import time
from typing import List, Dict, Any

# Page Config
st.set_page_config(
    page_title="BharatGenFinance - AI Equity & RAG Analyst",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling
st.markdown("""
<style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1E293B;
        margin-bottom: 0.2rem;
    }
    .sub-title {
        font-size: 1.0rem;
        color: #64748B;
        margin-bottom: 1.5rem;
    }
    .status-box {
        padding: 0.75rem 1rem;
        border-radius: 8px;
        margin-bottom: 1rem;
    }
    .status-online {
        background-color: #DEF7EC;
        color: #03543F;
        border: 1px solid #84E1BC;
    }
    .status-offline {
        background-color: #FDE8E8;
        color: #9B1C1C;
        border: 1px solid #F8B4B4;
    }
    .stChatMessage {
        border-radius: 10px;
    }
</style>
""", unsafe_allow_html=True)

# Session State Initialization
if "messages" not in st.session_state:
    st.session_state.messages = []

if "backend_url" not in st.session_state:
    st.session_state.backend_url = "http://localhost:8000"

if "backend_connected" not in st.session_state:
    st.session_state.backend_connected = False

if "gpu_info" not in st.session_state:
    st.session_state.gpu_info = {}

# Sidebar Configuration
with st.sidebar:
    st.image("https://img.icons8.com/isometric-folders/512/financial-analytics.png", width=64)
    st.title("Settings & Config")
    
    # Backend URL Input
    api_url = st.text_input(
        "Google Colab Backend API URL",
        value=st.session_state.backend_url,
        placeholder="https://xxxx.ngrok-free.app",
        help="Paste the public ngrok or tunnel URL generated by your Google Colab notebook."
    ).rstrip('/')
    
    st.session_state.backend_url = api_url

    # Check Connection Button
    if st.button("🔌 Check Connection", use_container_width=True):
        try:
            res = requests.get(f"{api_url}/health", timeout=5)
            if res.status_code == 200:
                data = res.json()
                st.session_state.backend_connected = True
                st.session_state.gpu_info = data.get("gpu", {})
                st.success("Connected to Colab Backend!")
            else:
                st.session_state.backend_connected = False
                st.error(f"Backend returned status code {res.status_code}")
        except Exception as e:
            st.session_state.backend_connected = False
            st.error(f"Connection failed: {e}")

    # Display Connection Status Badge
    if st.session_state.backend_connected:
        st.markdown("""
        <div class="status-box status-online">
            🟢 <b>Backend Online</b> (Colab GPU Active)
        </div>
        """, unsafe_allow_html=True)
        if st.session_state.gpu_info:
            gpu_name = st.session_state.gpu_info.get("name", "GPU")
            vram_used = st.session_state.gpu_info.get("vram_used_gb", 0)
            vram_total = st.session_state.gpu_info.get("vram_total_gb", 0)
            st.caption(f"🖥️ **Device**: {gpu_name}")
            st.caption(f"💾 **VRAM**: {vram_used:.1f} GB / {vram_total:.1f} GB")
    else:
        st.markdown("""
        <div class="status-box status-offline">
            🔴 <b>Backend Disconnected</b><br/>Please verify Colab URL.
        </div>
        """, unsafe_allow_html=True)

    st.divider()
    
    # Analysis & Inference Settings
    st.subheader("⚙️ Model Parameters")
    mode = st.selectbox(
        "Analysis Mode",
        ["RAG Document Q&A", "General Financial Chat", "Institutional Equity Analysis"],
        help="Institutional Equity Analysis applies institutional research prompts."
    )
    
    temperature = st.slider("Temperature", 0.0, 1.0, 0.7, 0.05)
    max_new_tokens = st.slider("Max New Tokens", 128, 2048, 512, 64)
    top_k = st.slider("RAG Top Chunks (Top-K)", 1, 10, 4)

    st.divider()
    if st.button("🗑️ Clear Chat History", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# Main Interface Header
st.markdown('<div class="main-title">📈 BharatGenFinance AI Analyst</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Powered by <b>FinanceParam</b> on Google Colab GPU & Google Drive Storage</div>', unsafe_allow_html=True)

# Tabs: Chat & Document Upload
tab_chat, tab_docs = st.tabs(["💬 Chat & Analysis", "📄 Document Indexing (RAG)"])

with tab_docs:
    st.header("Upload Financial Reports & Documents")
    st.write("Upload PDF, TXT, or CSV financial statements, annual reports, earnings call transcripts, or research notes to build your vector database.")
    
    uploaded_files = st.file_uploader(
        "Choose financial files",
        type=["pdf", "txt", "csv"],
        accept_multiple_files=True
    )
    
    if st.button("⚡ Process & Index Documents", type="primary"):
        if not uploaded_files:
            st.warning("Please select at least one file to upload.")
        elif not st.session_state.backend_connected:
            st.error("Backend server is disconnected. Check connection in the sidebar.")
        else:
            with st.spinner("Uploading and generating vector embeddings on Colab GPU..."):
                files_payload = []
                for f in uploaded_files:
                    files_payload.append(("files", (f.name, f.getvalue(), f.type)))
                
                try:
                    res = requests.post(f"{st.session_state.backend_url}/upload", files=files_payload, timeout=120)
                    if res.status_code == 200:
                        data = res.json()
                        st.success(f"Successfully processed {data.get('documents_processed', len(uploaded_files))} documents!")
                        st.info(f"Total chunks indexed in Vector Store: {data.get('total_chunks', 'N/A')}")
                    else:
                        st.error(f"Failed to process documents: {res.text}")
                except Exception as e:
                    st.error(f"Error communicating with backend: {e}")

    st.divider()
    st.subheader("📚 Indexed Documents Overview")
    if st.button("🔄 Refresh Document List"):
        if st.session_state.backend_connected:
            try:
                res = requests.get(f"{st.session_state.backend_url}/documents", timeout=5)
                if res.status_code == 200:
                    doc_data = res.json()
                    st.json(doc_data)
                else:
                    st.error("Failed to fetch documents list.")
            except Exception as e:
                st.error(f"Error fetching documents: {e}")
        else:
            st.warning("Backend is disconnected.")

with tab_chat:
    # Render Chat History
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            if "sources" in message and message["sources"]:
                with st.expander("📌 Retrieved RAG Sources"):
                    for idx, src in enumerate(message["sources"]):
                        st.markdown(f"**Source {idx+1}** ({src.get('source', 'Unknown')}):")
                        st.caption(src.get("text", ""))

    # Load System Prompt template if institutional equity analysis mode is selected
    system_instruction = ""
    if mode == "Institutional Equity Analysis":
        prompt_file = os.path.join(os.getcwd(), "prompt.txt")
        if os.path.exists(prompt_file):
            with open(prompt_file, "r") as f:
                system_instruction = f.read()

    # User Input Chat Box
    if user_input := st.chat_input("Ask a question about financial statements, equity valuation, ratios, or uploaded documents..."):
        # Append User Message
        st.session_state.messages.append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        # Assistant Response Placeholder
        with st.chat_message("assistant"):
            message_placeholder = st.empty()
            
            if not st.session_state.backend_connected:
                err_msg = "❌ **Backend Disconnected**: Please ensure your Google Colab FastAPI server is running and the URL in the sidebar is updated."
                message_placeholder.markdown(err_msg)
                st.session_state.messages.append({"role": "assistant", "content": err_msg})
            else:
                with st.spinner("FinanceParam model is thinking..."):
                    payload = {
                        "message": user_input,
                        "history": st.session_state.messages[:-1],
                        "mode": mode,
                        "system_prompt": system_instruction,
                        "temperature": temperature,
                        "max_new_tokens": max_new_tokens,
                        "top_k": top_k
                    }
                    
                    try:
                        res = requests.post(
                            f"{st.session_state.backend_url}/chat",
                            json=payload,
                            timeout=180
                        )
                        
                        if res.status_code == 200:
                            response_data = res.json()
                            bot_response = response_data.get("response", "No response generated.")
                            sources = response_data.get("sources", [])
                            
                            message_placeholder.markdown(bot_response)
                            
                            if sources:
                                with st.expander("📌 Retrieved RAG Sources"):
                                    for idx, src in enumerate(sources):
                                        st.markdown(f"**Source {idx+1}** ({src.get('source', 'Unknown')}):")
                                        st.caption(src.get("text", ""))

                            st.session_state.messages.append({
                                "role": "assistant",
                                "content": bot_response,
                                "sources": sources
                            })
                        else:
                            err_msg = f"API Error ({res.status_code}): {res.text}"
                            message_placeholder.error(err_msg)
                            st.session_state.messages.append({"role": "assistant", "content": err_msg})
                    except Exception as e:
                        err_msg = f"Failed to reach FastAPI backend: {e}"
                        message_placeholder.error(err_msg)
                        st.session_state.messages.append({"role": "assistant", "content": err_msg})
